extends: default

rules:
  line-length:
    max: 120  # Increase limit for GitHub Actions
  document-start: disable  # Disable requirement for ---
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']  # Allow on/off values
  comments:
    min-spaces-from-content: 1
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1